print ("hello world")
print ('bora bill')
print ("laele")
print ("amostradinho")
print ("87 é do sport")
print ("#fazer gol contra é facil")
print ("pq quando saimos compramos roupa nova se no lugar que vc foi ngm conhece suas roupas velhas...")
print ("sim")
print ("SEU SONHO ESTA REALIZADO MENINO")
print ("CRISTIANO DE BICICLETA!!!")